version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
    mem_limit: 2g

networks:
  esnet: